// ========== Supabase Type Helpers ==========
// These types provide type-safe database operations

import { SupabaseClient } from '@supabase/supabase-js';

// Import Database type (generated by Supabase)
// This should be generated using: npx supabase gen types typescript --local > lib/types/database.ts
import { Database } from '@/lib/types/database';

/**
 * Typed Supabase Client
 * Use this instead of the raw SupabaseClient for type safety
 */
export type TypedSupabaseClient = SupabaseClient<Database>;

/**
 * Table Row Types
 * Get the Row type from a table
 */
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

/**
 * Table Insert Types
 * Get the Insert type from a table (for creating new records)
 */
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

/**
 * Table Update Types
 * Get the Update type from a table (for updating records)
 */
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

/**
 * Enum Types
 * Get enum types from database
 */
export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T];

/**
 * Relationship Joins
 * Helper type for joining tables
 */
export type Relationships = Database['public']['Relations'];

/**
 * View Types
 * Get types from database views
 */
export type Views<T extends keyof Database['public']['Views']> =
  Database['public']['Views'][T]['Row'];

/**
 * Function Return Types
 * Get return types from database functions
 */
export type FunctionReturns<T extends keyof Database['public']['Functions']> =
  Database['public']['Functions'][T]['Returns'];
